### ISSUE TITLE
Possible bug with calculating lines.

### ISSUE THREAD

**Issue by tnlogy** [contourpy/contourpy#240]
Hi. We've have seen an issue with calculating lines for a dataset. In the code below, we tries to draw isolines around the area with value 15. But when running the code, we get lines around the wrong area. In most cases contourpy have worked fine for our rendering of maps, but in this case there seems to be something wrong. Any suggestions about why?

Here is some test code that prints the numpy arrays for the generated lines.
```
def test_contourpy():
    import numpy
    from PIL import Image, ImageDraw
    from contourpy import contour_generator

    z = numpy.array(
        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 200, 15, 15, 15, 15, 15, 15, 15, 0, 0],
         [0, 200, 20, 15, 15, 15, 15, 15, 15, 0, 0],
         [0, 200, 200, 15, 15, 15, 15, 15, 0, 0, 0],
         [0, 0, 200, 200, 15, 15, 15, 15, 0, 0, 0],
         [0, 0, 0, 0, 15, 15, 15, 15, 0, 0, 0],
         [0, 0, 0, 0, 0, 15, 15, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
        , dtype=numpy.float
    )

    im = Image.new('L', z.shape)
    draw = ImageDraw.Draw(im)
    cont_gen = contour_generator(z=z)
    lines = cont_gen.lines(15.0)
    xy = lines[0].flatten().tolist()
    draw.line(xy, fill=1)
    pix = numpy.array(im.getdata()).reshape(im.size[0], im.size[1])
    print("data:")
    print(z)
    print(pix)
```

And the output of the code (that generates lines around the area with 200, rather than 15):
```
data:
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0. 200.  15.  15.  15.  15.  15.  15.  15.   0.   0.]
 [  0. 200.  20.  15.  15.  15.  15.  15.  15.   0.   0.]
 [  0. 200. 200.  15.  15.  15.  15.  15.   0.   0.   0.]
 [  0.   0. 200. 200.  15.  15.  15.  15.   0.   0.   0.]
 [  0.   0.   0.   0.  15.  15.  15.  15.   0.   0.   0.]
 [  0.   0.   0.   0.   0.  15.  15.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0]
 [1 1 0 1 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
```

**Comment by ianthomas23** [comment]
There is no bug here. You have a number of grid points at the same z-level and you are asking for a contour line at exactly that z-level. What is expected to happen here? To show where the z-field exactly matches the contour level the algorithm would have to produce a filled polygon including all of those grid points, but you have asked for a contour line so producing a polygon is unacceptable.

What the algorithm does is classify each grid point as being above or below the contour level, and contour lines are produced for edges between grid points for which one end is above and one below the contour level. The full explanation is at https://contourpy.readthedocs.io/en/v1.0.7/description.html. Exactly matching the contour level has to be classified as either above or below the contour level, the convention is the latter. So in your example values from minus infinity up to and including 15.0 are classified as below the contour level, everything else is above. The output is consistent with this.

Another way of thinking about this is that as you cannot produce a polygon that spans the whole z=15 area then the contour line at that level needs to be either on the high side of the z=15 area (where z is increasing into adjacent grid points) or the low side (z decreasing into adjacent grid points). The convention is the former. (It could be "in the middle" of the z=15 area but "middle" is not well-defined in general).

In your example you can obtain what you would like to see using a contour level of e.g. `14.999`. 

The idea to take away here is that contouring is an interpolation algorithm for spatially-discretised continuous-z data. If your z-data is discretised too so that you have flat areas then you should never calculate contours at those z-levels or you will be disappointed. Probably if your z-data is discretised than contouring is a bad choice overall and you would be better using a polygonize algorithm such as in `xarray-spatial` or `gdal`.

**Comment by tnlogy** [comment]
Thank you for your feedback and explanation, much appreciated!

When trying I saw that `cont_gen.lines(15 - sys.float_info.epsilon*5)` seem to make it find the contour below 15. We will have to rethink a bit on how to handle this. Contourpy have worked really well for our other grib files that we have rendered, thank you for your effort in implementing this library.

**Comment by ianthomas23** [comment]
I am glad you've found an acceptable workaround. I will close this issue as no action is required.
