### ISSUE TITLE
No cp39-win32 wheels ?

### ISSUE THREAD

**Issue by Carreau** [contourpy/contourpy#253]
It looks like cp39-win32  were available for 1.0.7, but not 1.1.0. 

I don't particularly care, I just had a failing appveyor build on IPython, but I was anyway thinking of removing appveyor at some point. Plus I am testing on windows in GitHub action anyway, but just opened an issue in case it was an oversight.

Feel free to close.

**Comment by ianthomas23** [comment]
This is planned, there will be no more 32-bit wheels. This is stated at the top of the changelog (https://contourpy.readthedocs.io/en/v1.1.0/changelog.html#v1-1-0-2023-06-13) and discussed at #249.

**Comment by Carreau** [comment]
Ok, thanks ! Sorry for missing that.

**Comment by Carreau** [comment]
Ok, thanks ! Sorry for missing that.

**Comment by ianthomas23** [comment]
No problem!

**Comment by ianthomas23** [comment]
Given that NumPy are intending to continue shipping win32 wheels in the upcoming 1.26.0 release, I have restated shipping ContourPy win32 wheels. They are included in today's release candidate [1.1.1rc1](https://github.com/contourpy/contourpy/releases/tag/v1.1.1rc1) which also supports Python 3.12. I will retroactively add win32 wheels to the previous (1.1.0) release so that there isn't a gap.
